services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: code-editor-client
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:5000
    depends_on:
      - server
    networks:
      - app-network
    restart: unless-stopped

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: code-editor-server
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - GEMINI_API_KEY=AIzaSyB2SS_gS5eQzAhp8tZfkigP8-zxdfrzS5Y
      - JUDGE0_API_URL=https://judge0-ce.p.rapidapi.com
      - JUDGE0_API_KEY=be4084533cmsh28b07ad09f04548p10f8aejsn2957489c65a8
    volumes:
      - ./server/user_files:/app/user_files
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
