# Render.yaml for deploying the Code Editor application to Render.com
services:
  # Frontend Web Service
  - type: web
    name: code-editor-client
    runtime: docker
    repo: https://github.com/kingxshubham/code-editor.git
    region: oregon
    plan: free
    branch: master # Changed from 'main' to 'master' (verify the correct branch name)
    dockerfilePath: ./client/Dockerfile
    dockerContext: ./client
    healthCheckPath: /
    envVars:
      - key: VITE_API_URL
        fromService:
          name: code-editor-server
          type: web
          property: host # Use dynamic hostname instead of hardcoded URL
    pullRequestPreviewsEnabled: true

  # Backend Web Service
  - type: web
    name: code-editor-server
    runtime: docker
    repo: https://github.com/kingxshubham/code-editor.git
    region: oregon
    plan: free
    branch: master # Changed from 'main' to 'master' (verify the correct branch name)
    dockerfilePath: ./server/Dockerfile
    dockerContext: ./server
    healthCheckPath: /api/health
    envVars:
      - key: PORT
        value: 5000
      - key: GEMINI_API_KEY
        sync: false # Move to Render dashboard for security
      - key: JUDGE0_API_URL
        value: https://judge0-ce.p.rapidapi.com
      - key: JUDGE0_API_KEY
        sync: false # Move to Render dashboard for security
      - key: CORS_ORIGIN
        fromService:
          name: code-editor-client
          type: web
          property: host # Allow frontend hostname dynamically
