# Render Blueprint API
# https://render.com/docs/blueprint-spec

# The services section defines all the services that will be deployed
services:
  # Frontend React application
  - type: web
    name: code-mentor-client
    env: docker
    repo: https://github.com/shubham-kr2002/code_editor.git
    dockerfilePath: ./client/Dockerfile
    dockerContext: ./client
    plan: free
    branch: main
    numInstances: 1
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        fromService:
          name: code-mentor-server
          type: web
          property: host # Changed from 'url' to 'host'

  # Backend Node.js server
  - type: web
    name: code-mentor-server
    env: docker
    repo: https://github.com/shubham-kr2002/code_editor.git
    dockerfilePath: ./server/Dockerfile
    dockerContext: ./server
    plan: free
    branch: main
    numInstances: 1
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: GEMINI_API_KEY
        value: AIzaSyB2SS_gS5eQzAhp8tZfkigP8-zxdfrzS5Y # Pre-filled but can be changed during deployment
      - key: JUDGE0_API
        value: https://judge0-ce.p.rapidapi.com
      - key: JUDGE0_KEY
        value: be4084533cmsh28b07ad09f04548p10f8aejsn2957489c65a8 # Pre-filled but can be changed during deployment
      - key: CORS_ORIGIN
        fromService:
          name: code-mentor-client
          type: web
          property: host # Changed from 'url' to 'host'
